### ISSUE TITLE
Choosing the software license for the main repository

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#13]
Hi @open-sci/don-t-lock-up and @open-sci/la-chouffe,

As anticipated in [one of the past lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_33), we have to specify the license for all the software available in our [main repository](https://github.com/open-sci/2021-2022/). My preference would be to use the [ISC license](https://opensource.org/licenses/ISC) but I am happy to use another one if you think it is more appropriate for our course.

What do you think? Please start a discussion as comments on this issue.

**Comment by chiarasharp** [comment]
I personally think that is ISC is totally appropriate for our project as it is very permissive and short, so that its purpose is clear to the beginning. But we could also take in consideration to use a very similar license such as the [MIT license](https://opensource.org/licenses/MIT), that is officialy approved by the Open Source Initiative.

**Comment by dbrembilla** [comment]
I noticed that most of the licences are actually similar, with the exception of the line 

> _'Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.'_


That is present, in various forms, in many of the licences (e.g. MIT, [Boost](https://opensource.org/licenses/BSL-1.0)). Does this mean that the licence is limited? Is this similar to the copyleft clause? 
In the [MIT-0](https://opensource.org/licenses/MIT-0) licence this is not present. 
In the end, I'd choose either the MIT-0 if this limitation is to be avoided. Otherwise I'd choose the MIT or ISC licences.

**Comment by ChiaraCati** [comment]
I think what you have already listed works well for our purpose,  I also found the [Non-profit Open Source License (v 3.0)](https://opensource.org/licenses/NPOSL-3.0), that could work for a project like ours, but it is mandatory that the authorship owner is a non-profit itself. What do you think about it?

**Comment by ConstiDami** [comment]
From what I could read from different licenses, I also think that ISC is the most appropriate, and actually following @dbrembilla's comment, there is the [Zero-Clause BSD (0BSD)](https://opensource.org/licenses/0BSD) which is an alteration of ISC, removing the part about the presence of copyright notice:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

(ISC License)

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.

(0BSD)

So same for me, if it is removing a limitation I would go for that one, but ISC or MIT are fine too!

As for the license proposed by @ChiaraCati I would personaly prefer a simpler one, because I am not sure that for our project the specification of non-profit is a crucial one, and from what I understood, any reuse of the software must include the full text of the license which is less permissive than the ones previously cited.

**Comment by umut-kucuk** [comment]
Considering the scope and the context of our projects, I think we should choose a license that is as permissive as we can. MIT and ISC licenses stand out among others as the most used permissive licenses. ISC has the least text, but MIT is also perfectly suitable for our purposes. Personally, I would choose either ISC or MIT licenses, however, we can also choose from among the other suggested permissive licenses.

**Comment by GiuliaVenditti** [comment]
As my colleagues have already noted, there are a large number of Free-Libre / Open Source Software (FLOSS) licenses, but only a few are widely used. 
Widely used licenses tend to be compatible, which means that the software can be combined to produce a larger work. First of all, a choice should be considered between "permissive" licenses (MIT, BSD, ISC), which allow the software to become proprietary (ie not FLOSS), and “weakly protective” (LGPL) licenses, a trade-off between permissive and strongly protective licenses. These prevent the software components from becoming proprietary, but allow it to be part of a larger proprietary program. In this way we could guarantee  software reuse, modification and unions, maintaining a FLOSS license. The [GNU Lesser General Public License (LGPL)](https://opensource.org/licenses/lgpl-license) is the most popular weakly protective license and has version 2.1 ([LGPLv2.1](https://opensource.org/licenses/LGPL-2.1)) and 3 ([LGPLv3](https://opensource.org/licenses/LGPL-3.0)). LGPLv2.1 gives you permission to relicense the code with any version of the GPL from GPLv2.

Since the trend of the discussion is about "permissive" licensing, I would like to point out that, even though ISC is a functional equivalent of MIT, the difference is that MIT also explicitly allows sub-licensing, while ISC does not prohibit it as long as the original license is somewhere. This confuses the process of combining an ISC licensed work with another product. Therefore, explicitly allowing sub-licensing can make software reuse easier by making it less confusing and less scary for casual developers. So, if you want the sublicense option to be open, MIT should be preferable, for the sake of clarity to the general user.

**Comment by chiarasharp** [comment]
So, going from what Giulia said, I think it comes down to choosing if we want the clear and specific permissive license that is MIT or the stripped down version of that, ISC.
I personally think that using MIT would be better because I don't think that the fact the ISC assumes things to be implicit is very inclusive. Even though it seems to be more simple, I would prefer that all of the implications of our license were written explicitly for the readers that are not legalities experts.

**Comment by AlessandroBertozzi** [comment]
I agree with focusing on the choice between ISC and MIT. Both protect the two fundamental aspects of our project: permissiveness and essentiality.
I believe the two licenses are functionally the same. The only difference is the type of language: the ISC does not use language deemed unnecessary under the Berne Convention. I attach here the source of Wikipedia and another article from which I took the information.

_ISC license_ (https://en.wikipedia.org/wiki/ISC_license)
```
The ISC license is a permissive free software license published by the Internet Software Consortium, now called Internet Systems Consortium (ISC). It is functionally equivalent to the simplified BSD and MIT licenses, but without language deemed unnecessary following the Berne Convention.
```
_Open Source Software Licenses 101: The ISC License_ (https://fossa.com/blog/open-source-software-licenses-101-isc-license/)
```
For all intents and purposes, these two licenses are the same. The ISC License simply removes language that would be considered extraneous according to the Berne Convention. The MIT License is much more explicit in its wording, stating outright that users have the right to sublicense, modify, copy, and/or distribute the code.
```
So I think the ISC is already more than enough for our intent. I would choose MIT though, just to include all the concerns raised in the discussion just above.

**Comment by essepuntato** [comment]
Ok guys, thanks for the interesting discussion. Thus, please reach an agreement and add the licence to the main repository, by creating a file "LICENCE.md" with the licence there - please see the [repository of the previous year](https://github.com/open-sci/2020-2021) as an example.

**Comment by ConstiDami** [comment]
We all agreed on the MIT license, so I added it to the main repository.
