### ISSUE TITLE
Revision of material - team Don't lock up

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2021-2022#29]
Dear @open-sci/don-t-lock-up,

Please find here attached my comments on all your material. You have to address all of them and, once finalised, close this issue with a comment containing your reply to each of the points I have highlighted. There is no specific deadline to complete this task, thus please take your time.

Please, be aware that some modifications in some documents may affect also modifications in other documents. As a final note, please remember to keep your notebooks up-to-date.

After closing this issue, please remember to update your material.md file by specifying the references to the new version of all your documents.

As usual, for further doubts, do not hesitate to contact me in the Slack channel or just comment on this issue here.

# General comments from the presentation

The following comments and questions should be addressed and may result also in the modification of some of the material prepared for the project:
- It is important that both the groups are aligned and use the same dumps, in particular the DOAJ one, which is the one in common. Please check that this is so. If this is not true, please use the most updated dump among those ones taken by the groups.
- During the presentation, it was not clear which datasets have been downloaded for the study. Those should be specified and appropriately cited or mentioned.
- The keyword "open_cit" in the JSON created refers to the citations received by an article or to the citations done by the article?
- When you did the group-by-year task, you said you identified some errors. Which errors are those? Please provide a description with categories of errors, with also the counts for each category.
- You mentioned a big difference between the citations received and done by DOAJ articles. Can you explain the reason for it?
- Is the proportion between citations received and done the same across all the journals considered in the study?
- Is the trend shown during the presentation weighted according to the increment of available open access articles in DOAJ? You need to be sure that such a trend does not depend only on the increment of OA articles in DOAJ, in particular.
- Several prior studies analysing similar dimensions have been introduced during the presentation. What were the outcomes of such previous studies and how do they compare with those one introduced in the project? Do they in agree or there are shades of disagreement? In the latter case, can you envision why?
- It is not clear why a discussion of predatory journals is functional to the outcome of this study. It is important to clarify this aspect.
- Do all journals in DOAJ have a seal? If not, did you consider only seal journals for your study?
- It would be important to add also a journal self-citation analysis, in order to highlight the percentage of citations that a journal does to itself. In addition, measuring the ratio between citations received and done con provide a view of how journals cite/are cited.
- Please be explicit about the limitation of the study, e.g. that not considering citations to non-DOI entities is a possible limitation for the analysis.
- Please be explicit about any error analysis in the paper (e.g., how did you handle dates that are null?)
- Justify the choice of using pickle with regard to other possible formats.
- Please consider showing, in the various visualisation, also some views that consider the time (e.g. year of publication, etc.).
- Please clarify that difference any difference between the citations done and received is not definite and necessarily correct, since it could be derived from a lack of metadata in the sources used for the study (this is another limitation to add to those mentioned above).
- During the introduction, someone said that self-citations can be used as a measure of plagiarism. This claim is bold and should be strongly supported by data and/or other works on the matter.
- Be explicit about the publication date of the dump.
- It is important to have the data presented grouped by disciplines, in order to have cross-comparisons against different fields.
- The slides presented are not linked to the material.md file.

# DMP

General points:
- there are a few typos, please correct them.
- if you mention something in the description, please add links to it (e.g., when you mention Dublin Core, add the link to the vocabulary used)

## Dataset for Coverage of DOAJ journals' citations through OpenCitations
- 3.1.1.8: if it is possible, please add a brief description of the naming convention (how it works)
- 3.1.1.22: you should describe how such quality is defined/computed.

## Software for Coverage of DOAJ journals' citations through OpenCitations
- 1.1.3: is software a format? It is possible that you had to choose from a list of fixed possibilities, though.
- 3.1.1.8: if it is possible, please add a brief description of the naming convention (how it works)
- 3.1.1.15: I do not think you share the compiled version (pyc) of your files, rather just the  Python plain version (py), right?

# Protocol

The data visualisation part is, practically speaking, with no details. It would be important to know here which graphs you plan to use to show which part of the data, at least. In addition, please add links to relevant material if they are missing (e.g. a link to the GitHub repository of the group, which is mentioned.)

Please just check again the text to correct a few typos.

# Software

The README.md in the GitHub repository does not contain an appropriate introduction on how I can pass the input to the software itself. For instance, suppose that I want to run again your software with more updated sources. How can I do it? Where do I have to put them? This must be clear reading the README. 

Finally, the item on Zenodo describing the software is not linked via GitHub. I think you did not use the GitHub+Zenodo approach for uploading it on GitHub, as introduced during the lectures. This would guarantee that also a new version of the software will be assigned with version DOIs and automatically linked with the GitHub repository and the previous versions uploaded on Zenodo. Please, use the appropriate method to upload the software.

# Article

"Abstract": it should be the same structured abstract you have prepared in advance. Why here does it have a different format?

"An ontology named OpenCitation Corpus has been built in order to produce and share open citation data": the OpenCitations Corpus was not an ontology, but a dataset. The ontologies used to describe the data in the Corpus were the SPAR Ontologies, indeed.

The introduction seems to be a bit fragmented and, often, there is no natural flow between a paragraph and the following one. Please revise it to make the article more smooth in reading.

Also, the methodology does not include several details that are expected there. There are no links to the specific dumps used for the analysis, and no explicit citation to all the relevant material produced by the group (DMP, protocol and software). How can a reader replicate the study by reading the current status of the methodology? Please, revise it accordingly.

"17’570": this way of representing numbers is not UK/US compliant. Please, use a normal comma (",") for separating groups of digits in big numbers, and a dot (".") for the fractional part, e.g. 12,999.45.

"Number of articles processed": did they include also those ones without DOIs? It is not clear from table 1.

In tables 3 and 4, please also weigh the number of citations considering the number of the articles, in order to have a clearer picture of the numbers.

Figure 2: you should justify somehow that the last bar (2022) is smaller than the previous one.

In the discussion section, you should, indeed, discuss your result adding some considerations and speculations, comparing them with other studies and showing the limitation of the study. None of these aspects are present in the section. As such, it must be revised and extended appropriately.

Please, carefully read the article again to correct typos and other mistakes.

**Comment by AlessandroBertozzi** [comment]
Dear @essepuntato, here is our response to your revision of the project.

# Answers to `general comments` section

* _It is important that both the groups are aligned and use the same dumps, in particular the DOAJ one, which is the one in common. Please check that this is so. If this is not true, please use the most updated dump among those ones taken by the groups._

We coordinated with the other group to make sure to share the same dump from DOAJ (DOAJ articles dump of May 01, 2022).



* _During the presentation, it was not clear which datasets have been downloaded for the study. Those should be specified and appropriately cited or mentioned._

We specified the version of the dumps we used in the “Materials” section of the protocol, in the DMP, in the article and in the README of the GitHub repository.



* _The keyword "open_cit" in the JSON created refers to the citations received by an article or to the citations done by the article?_

We changed the keyword to make it clearer: we adopted “citations_to_DOAJ” for the citations a DOAJ journal does to DOAJ journals and “cited_by_DOAJ” for the citations a DOAJ journal receives from DOAJ journals.



* _When you did the group-by-year task, you said you identified some errors. Which errors are those? Please provide a description with categories of errors, with also the counts for each category._

We encountered different kinds of errors regarding the dates of the citations in the task that grouped the citations by year. We found many null dates and dates that were in a year too far in the future from the current 2022.                                                                                                     At the beginning, we thought that every citation with a date after 2022 was an error, but we found out that there were many articles from 2024 that were actually reporting that publication year in their main page.                                                                                                                             So we decided to consider everything past 2024 an error. Here are all the categories of error we encountered:



1. Citations with null dates, all the citations coming or going or both from DOAJ journals that had null dates
2. Citations with wrong dates, all the citations coming or going or both from DOAJ journals that had errors in the dates, particularly that had a year after 2024. This is because we checked and there were citations with dates coming “from the future” (so after 2022, the year of our research) that were actually correct, but stayed before 2024.
3. Articles with missing DOIs

We put all the errors in the “errors” directory divided by files with the name of the correspondent category. We then counted all the elements on each file and created the errors.json file with all the counts.



* _You mentioned a big difference between the citations received and done by DOAJ articles. Can you explain the reason for it._

The citation data was incomplete: only the citations made by the journal were included, the citations that the journal received were missing. The data was not updated.



* _Is the proportion between citations received and done the same across all the journals considered in the study?_

We created a new column in the final data about the journals for the proportion/ratio between these things and added some visualizations about it.                                                                    We plotted the difference between cited and citing of the citations divided by year of all DOAJ and of the biggest DOAJ journal. Also for the cited by DOAJ and citations to DOAJ.



* _Is the trend shown during the presentation weighted according to the increment of available open access articles in DOAJ?_

We created columns about the percentage of citations to and citing by DOAJ in the number of cited and citing of every journal of the dataset.                                                                             We also created some visualizations that show the timeline of these percentages in the years, in addition to the timeline of just the numbers.



* _You need to be sure that such a trend does not depend only on the increment of OA articles in DOAJ, in particular. Several prior studies analysing similar dimensions have been introduced during the presentation. What were the outcomes of such previous studies and how do they compare with those one introduced in the project? Do they in agree or there are shades of disagreement? In the latter case, can you envision why?_

A similar study on DOAJ (Pandita & Singh, 2022) uses the public data dump of DOAJ and analyze_ _the growth of Open Access journals indexed in DOAJ between 2002 to 2021. The study is based on the number of articles and journals and its change over the years.

The study compares the continents and countries and reveals the leading ones in Open Access publishing. Addition to these study also analyze the distribution of the journals based on language and subject.

Before proceeding with the outcomes of this study it is important to know that the authors might have a bias against the open access publishing model. Authors refer to WoS and SCOPUS as “good indexes” several times. The study makes accusations based on not being indexed in a commerical citation database such as SCOPUS. Following pharagraph is a clear example of this aspect: _“The unprecedented growth of new journals in different subject disciplines across Asian countries has somewhere tagged the region as home of predatory journals as well. Accordingly, researchers in their study while assess the growth of research journals in India found that 15,631 new research journals were launched in India from 2005 to 2014 at an annual growth of 31.44%, with majority 82.36% journals published in English language. However, only 3% of research journals published from India stand indexed in SCOPUS, which is a very miniscule number given the total number of research journals published across India.”_

Even though study uses the DOAJ public data dump its approach using the Microsoft Excel in order to proceed mathematical operations. Study reveals the exponential growth in journals indexed in DOAJ. The average annual growth is 51.46%. _“The maximum 14.32% research journals were indexed in the year 2017, followed by 13.12% in 2018 and 12.86% in 2020.”_ (Pandita & Singh, 2022, p. 12) This results are parrallel to our results based on citations. “_When we look at the output data of our study, it is possible to witness an exponential growth in DOAJ citations, especially in the period between 2017-2020.”_ (Bertozzi, Alessandro et al., 2022, p. 11) From this, we can say that the number of journals indexed in DOAJ and the citations have increased proportionally over the years.

There are also some studies (Saadat & Shabani, 2012) that focus directly on citation data. But it measures the value of DOAJ journals by comparing citations found in proprietary citation databases such as the Web of Science (WoS). Saadat and Shabani (2012) analyze the DOAJ journals that received citations from the articles indexed in Web of Science, the study consists of the years between 2003 and 2008. The main outcome of the study is that only 10.87% of the DOAJ journals received citations from the articles that were indexed in WoS and the total number of citations was 19050. The average number of citations for each journal was 6.45. Natural science journals received most of the citations and the Art and Humanities journals received the least. (Saadat & Shabani, 2012, p. 4) First and foremost the main issue is the dilemma of measuring the value of Open Access journals by the citations they received from the journals that are not in the Open Access domain but in closed Toll Access publishing domain. In this context, there is a strict positioning on the approach.

In general, the main points that can be easily observed from all studies are the increase in published open access journals and the citations received by these journals over the years. In addition, based on the studies, it can be said that natural science journals are the most published and cited field in open access.

It is possible to observe a bias against open access, especially in studies on open access published in the toll access model, but of course, this is a claim that needs to be examined with much more samples. 



* _It is not clear why a discussion of predatory journals is functional to the outcome of this study. It is important to clarify this aspect._

During the literature review, we observed that an argument frequently encountered is the predatory journal phenomenon (Bartling & Friesike, 2014), (Laine & Winker, 2017),  (Duc et al., 2020), (Basson et al., 2022), (Pandita & Singh, 2022). Articles on DOAJ, Open Access, and Open Science mention this phenomenon as an obstacle to the open access domain. Predatory journals basically take advantage of APCs (Article Processing Charges) and publish any material without proper peer review, accuracy of data, and most do not even check for plagiarism. We have deduced from the literature that an important sign of predatory journals is the abnormal difference between the citations they make and the citations they receive. And in our early results, we came across many journals that done thousands of citations, but did not receive even a single citation. Based on the literature review and the initial results of the study, there was an undeniable match. Later, when we checked the journals one by one outside of the DOAJ and OpenCitations data, we saw that they actually received citations but did not appear in the results. This means that our initial data was not updated. We have included this process in our article as it is.

(Bertozzi, Alessandro et al., 2022) _“In the data we obtained as a result of the study, we observed that some journals did not receive any citations, but they made a large number of citations. However, when we examined the aforementioned journals individually, we came to the conclusion that this situation is due to the fact that the current data has not been updated yet. In fact, DOAJ frequently inspects its database as a precaution against predatory publishers, and accepts and evaluates readers' feedback on journals they find suspicious._” https://doi.org/10.5281/zenodo.6574742

Another important aspect is that predatory journals are a phenomenon that is also abused by those who oppose the open access publishing model. It is frequently referred to in order to accuse and slender the entire environment of open access. However, this is a claim that requires further research and study, so we did not mention this hypothesis in the article. And, we just discussed predatory journals in general terms as it occurred many times during the literature research and based on the early results of an ongoing study. In addition, we talked about the measures taken by DOAJ against such journals.

References: 

Laine, C., & Winker, M. A. (2017). Identifying predatory or pseudo-journals. Biochemia Medica, 27(2), 285–291.[ https://doi.org/10.11613/BM.2017.031](https://doi.org/10.11613/BM.2017.031)

Pandita, R., & Singh, S. (2022). A Study of Distribution and Growth of Open Access Research Journals Across the World. Publishing Research Quarterly, 38(1), 131–149. https://doi.org/10.1007/s12109-022-09860-x

Bartling, S., & Friesike, S. (Eds.). (2014). Opening Science. Springer International Publishing.[ https://doi.org/10.1007/978-3-319-00026-8](https://doi.org/10.1007/978-3-319-00026-8)

Duc, N., Hiep, D., Thong, P., Zunic, L., Zildzic, M., Donev, D., Jankovic, S., Hozo, I., & Masic, I. (2020). Predatory Open Access Journals are Indexed in Reputable Databases: A Revisiting Issue or an Unsolved Problem. Medical Archives, 74(4), 318.[ https://doi.org/10.5455/medarh.2020.74.318-322](https://doi.org/10.5455/medarh.2020.74.318-322)

Basson, I., Simard, M.-A., Ouangré, Z. A., Sugimoto, C. R., & Larivière, V. (2022). The effect of data sources on the measurement of open access: A comparison of Dimensions and the Web of Science. PLOS ONE, 17(3), e0265545.[ https://doi.org/10.1371/journal.pone.0265545](https://doi.org/10.1371/journal.pone.0265545)


* _Do all journals in DOAJ have a seal? If not, did you consider only seal journals for your study?_

“Around 10% of journals indexed in DOAJ have been awarded the Seal.” No, we did not consider only the seal journals since our base research questions focus on the whole citation data in DOAJ.



* _It would be important to add also a journal self-citation analysis, in order to highlight the percentage of citations that a journal does to itself._

We created a new column in the final data about the journals for the self citations and plotted the 20 most self-citing journals.



* _In addition, measuring the ratio between citations received and done can provide a view of how journals cite/are cited._

We created a column with the ratio between citing and cited. We plotted the difference between cited and citing of the citations divided by year of all DOAJ and of the biggest DOAJ journal. Also for the cited by DOAJ and citations to DOAJ.



* _Please be explicit about the limitation of the study, e.g. that not considering citations to non-DOI entities is a possible limitation for the analysis._

We did not consider the citations to non-DOI entities, and this is our limitation for the analysis. We added a paragraph in the article about the limitations and errors we encountered in the data dumps.



* _Please be explicit about any error analysis in the paper (e.g., how did you handle dates that are null?)_

When we encountered missing data and errors in the data dumps, we collected the errors in separate files and published them. The file “article_without_dois.json” contains all the articles from the DOAJ dump that don’t have a DOI registered. When analyzing our data, we saw that each journal always had at least an issn or an eissn, but some articles registered only one or the other while the journal data dump indicated both. In order to align the dumps and make sure to have no duplicates, we created a unique key for each journal by concatenating the issn and the eissn. 

We encountered different kinds of errors regarding the dates of the citations in the task that grouped the citations by year. We found many null dates and dates that were in a year too far in the future from the current 2022. At the beginning, we thought that every citation with a date after 2022 was an error, but we found out that there were many articles from 2024 that were actually reporting that publication year in their main page. We collected all the errors divided by category in json files in a directory called errors and every file is called like the correspondent category. We then counted the errors for each category to create the errors.json file.



* _Justify the choice of using pickle with regard to other possible formats._

Since we don’t need to publish this specific data but we just need it for the next computation in another python script, we judged it was the most practical data format for this. We used JSON for publishing, and pickle for internal use. 



* _Please consider showing, in the various visualisation, also some views that consider the time (e.g. year of publication, etc.)._

We created more visualizations that considered years.



* _Please clarify that difference any difference between the citations done and received is not definite and necessarily correct, since it could be derived from a lack of metadata in the sources used for the study (this is another limitation to add to those mentioned above)._

The citation data was incomplete: only the citations made by the journal were included in COCI, the citations that the journal received were missing. The data was not updated. This is the main reason of abnormal difference.



* _During the introduction, someone said that self-citations can be used as a measure of plagiarism. This claim is bold and should be strongly supported by data and/or other works on the matter._

No member of our team recalls making this claim. If we led the audience to believe it was part of our research or a shared opinion among us, we apologize for the bad formulation. 



* _Be explicit about the publication date of the dump._

Already adressed, we specified the date of the dumps inside the protocol, the DMP, the article and the README of the GitHub repository.



* _It is important to have the data presented grouped by disciplines, in order to have cross-comparisons against different fields._

We created more visualizations that considered the various subjects of the journals.



* _The slides presented are not linked to the material.md file._

We linked the presentation to the material.md file.

# Answers to `DMP` section



* _there are a few typos, please correct them._

We corrected the typos.



* _if you mention something in the description, please add links to it (e.g., when you mention Dublin Core, add the link to the vocabulary used)_

We added the missing links.



* _3.1.1.8: if it is possible, please add a brief description of the naming convention (how it works)_

We added a description of the naming convention.



* _3.1.1.22: you should describe how such quality is defined/computed._

We changed the answer to “no”. We decided to apply for our project the same indication as the Zenodo documentation in terms of data quality. It specifies the following :”All information is provided “as-is”, and the user shall hold Zenodo and information providers supplying data to Zenodo free and harmless in connection with the use of such information.” 



* _1.1.3: is software a format? It is possible that you had to choose from a list of fixed possibilities, though._

Yes, it was in a list of fixed possibilities. We could have chosen “Other” but since “Software was in the list we deemed it was appropriate here.



* _3.1.1.8: if it is possible, please add a brief description of the naming convention (how it works)_
* _3.1.1.15: I do not think you share the compiled version (pyc) of your files, rather just the Python plain version (py), right?_

We changed the type of file to “Python Script File”

# Answers to `protocol` section



* _The data visualisation part is, practically speaking, with no details. It would be important to know here which graphs you plan to use to show which part of the data, at least. In addition, please add links to relevant material if they are missing (e.g. a link to the GitHub repository of the group, which is mentioned.). Please just check again the text to correct a few typos._

We corrected the problems specifying the titles of the resulting graphs and their purpose. Also the typos.

# Answers to `software` section



* _The README.md in the GitHub repository does not contain an appropriate introduction on how I can pass the input to the software itself. For instance, suppose that I want to run again your software with more updated sources. How can I do it? Where do I have to put them? This must be clear reading the README._

We have added an updated version of the README.md file with specifications on how to start the programme.



* _Finally, the item on Zenodo describing the software is not linked via GitHub. I think you did not use the GitHub+Zenodo approach for uploading it on GitHub, as introduced during the lectures. This would guarantee that also a new version of the software will be assigned with version DOIs and automatically linked with the GitHub repository and the previous versions uploaded on Zenodo. Please, use the appropriate method to upload the software._

We uploaded both the version before and after the revision of the projects with the correct method.

# Answers to `article` section



* _"Abstract": it should be the same structured abstract you have prepared in advance. Why here does it have a different format?._

It has the exact structure with the one that was prepared in advance. Only difference is the title? 



* _"An ontology named OpenCitation Corpus has been built in order to produce and share open citation data": the OpenCitations Corpus was not an ontology, but a dataset. The ontologies used to describe the data in the Corpus were the SPAR Ontologies, indeed._

We updated the sentence like this: _A dataset named OpenCitation Corpus has been built in order to produce and share open citation data_. 



* _The introduction seems to be a bit fragmented and, often, there is no natural flow between a paragraph and the following one. Please revise it to make the article more smooth in reading._

In order to be smoother and to correct the fragmented structure, transition sentences were added to ensure the connection between the paragraphs.



* _Also, the methodology does not include several details that are expected there. There are no links to the specific dumps used for the analysis, and no explicit citation to all the relevant material produced by the group (DMP, protocol and software). How can a reader replicate the study by reading the current status of the methodology? Please, revise it accordingly._

The links for the DMP, protocol and the software added to the article as footnotes.



* _"17’570": this way of representing numbers is not UK/US compliant. Please, use a normal comma (",") for separating groups of digits in big numbers, and a dot (".") for the fractional part, e.g. 12,999.45. Numbers in the article updated with “,” or “.”_

The change has been made.



* _"Number of articles processed": did they include also those ones without DOIs? It is not clear from table 1._

Yes “Number of articles processed” refers to all articles which include the articles also without a DOI. The number of total articles with DOI is 5.8 million. New row added Number of articles with DOIs.



* _In tables 3 and 4, please also weigh the number of citations considering the number of the articles, in order to have a clearer picture of the numbers. Figure 2: you should justify somehow that the last bar (2022) is smaller than the previous one._

Data dump includes the data until its publication. Naturally it is not complete. That is the reason year 2022 is smaller than the previous one (2021). Footnote added to the article



* _In the discussion section, you should, indeed, discuss your result adding some considerations and speculations, comparing them with other studies and showing the limitation of the study. None of these aspects are present in the section. As such, it must be revised and extended appropriately._

The discussion part extended and comparison with other studies on the same subject added. Limitation of the study also stated in a different paragraph.



* _Please, carefully read the article again to correct typos and other mistakes._

We corrected the typos.

**Comment by essepuntato** [comment]
Could you please update the file material.md to point to the last versions of all the documents and data you have produced, please?

**Comment by essepuntato** [comment]
Beside the previous comment, many congratulations since your modifications address all the points mentioned in my initial comment, and I am happy with the result!

**Comment by ConstiDami** [comment]
@essepuntato We updated the file material.md. Thank you!
